services:
  erp-auth:
    build:
      context: .
      dockerfile: Dockerfile
    develop:
      watch:
        - action: rebuild
          path: .
          ignore:
            - bin/
            - obj/
    container_name: erp-auth-service
    ports:
      - "5001:8080"
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
    networks:
      - erp-network

  mongo:
    image: mongo:7
    container_name: erp-auth-mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MongoSettings__Username}
      MONGO_INITDB_ROOT_PASSWORD: ${MongoSettings__Password}
      MONGO_INITDB_DATABASE: ${MongoSettings__DatabaseName}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    networks:
      - erp-network

volumes:
  mongo_data:

networks:
  erp-network:
    external: true
    name: erp-network